import Head from "next/head"
import Layout from "@/components/layouts/Layout"

function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1 className="text-3xl text-slate-800 dark:text-slate-300 font-bold underline">
          Hello world!
        </h1>
        <ul>
          {data?.map((item) => (
            <li key={item.id} className="text-slate-800 dark:text-slate-300">
              {item.name}
            </li>
          ))}
        </ul>
      </main>
    </>
  )
}

export const getServerSideProps = async ({ req }) => {
  if (!req.headers.cookie) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    }
  }
  const response = await fetch("https://jsonplaceholder.typicode.com/users")
  const result = await response.json()

  return {
    props: {
      data: result,
    },
  }
}

export default Home

Home.getLayout = (page) => <Layout>{page}</Layout>
