import apiClient from "@/lib/apiClient"
import Head from "next/head"
import Layout from "@/components/layouts/Layout"

// import { redirect } from "next/dist/server/api-utils"

function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <ul>
          {data?.map((item) => (
            <li key={item.id}>{item.name}</li>
          ))}
        </ul>
      </main>
    </>
  )
}

export const getStaticProps = async (context) => {
  const response = await apiClient().get(
    "https://jsonplaceholder.typicode.com/users"
  )

  return {
    props: {
      data: response.data,
    },
  }
}

export default Home

Home.getLayout = (page) => <Layout>{page}</Layout>
